config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homes#show'

  resources :users, only: [:show, :edit, :update]
  resources :posts, only: [:new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, :body, presence: true

	belongs_to :user

	delegate :username, to: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy

  validates :username, presence: true

  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation, :remember_me] )
      devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :username, :email, :password, :remember_me] )
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :password_confirmation, :current_password] )
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def show
		@posts = Post.all
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!

	def new
		@post = Post.new
	end

	def create
		@post  = current_user.posts.new(post_params)
		if @post.save 
			redirect_to root_url
		else
			render :new
		end
	end

	private

		def post_params
			params.require(:post).permit(:title, :body)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!, only: [:edit, :update]
	before_action :check_authorization, only: [:edit, :update]

	before_action :set_user

	def show
	end

	def edit
	end

	def update
		if @user.update(user_params)
			redirect_to @user
		else
			flash.now[:alert] = "Something went wrong. Please try again!"
			render :edit
		end
	end

	private
		def check_authorization
			unless current_user.id == params[:id].to_i
				redirect_to root_url
			end
		end

		def set_user
			@user = User.find(params[:id])
		end

		def user_params
			params.require(:user).permit(:username, :description, :avatar)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def avatar_for(user, options = { size: 80 })
		size = options[:size]
		if user.avatar?
			image_tag @user.avatar.url(:thumb), width: size, class: 'avatar-image'
		else
			image_tag "default-avatar.jpg", width: size, class: 'avatar-image'
		end
	end
end

app/views/homes/show.html.erb
<h1>MyApp</h1>

<div class="posts">
	<%= render @posts %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Medium</a>
    <ul class="nav navbar-nav navbar-right">
		<li><%= link_to "Write a story", new_post_path, class: "button" %></li>
    <% if user_signed_in? %>
      <li><%= link_to(avatar_for(current_user, size: 30), current_user) %></li>
      <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "button" %></li>
    <% else %>
    	<li><%= link_to "Sign in/ Sign up", new_user_session_path, class: "button" %></li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "layouts/header" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<%= post.user.username %>
<%= post.title %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<div class="error">
			<h2>
				<%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:
			</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg%> </li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<%= f.label :title %>
	<%= f.text_field :title %>

	<%= f.label :body %>
	<%= f.text_area :body %>

	<%= f.submit "Publish" %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= form_for(@user, html: {multipart: true}) do |f| %>

	<%= f.label :username %>
	<%= f.text_field :username %>

	<%= f.label :description %>
	<%= f.text_area :description %>

	<%= f.file_field :avatar %>

	<%= f.submit "Save Changes" %>
<% end %>

app/views/users/show.html.erb
<h1>Profile for <%= @user.username %></h1>

<%= avatar_for(@user) %>

<%= @user.description %>

<%= link_to "Edit", edit_user_path(@user) %>